add this file

diff --git a/web_stack_debugging_0/0-give_me_a_page b/web_stack_debugging_0/0-give_me_a_page
--- a/web_stack_debugging_0/0-give_me_a_page
+++ b/web_stack_debugging_0/0-give_me_a_page
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash
 #
-## Start Apache with sudo
-#sudo service apache2 start
+## Start Apache if it's not running
+#service apache2 status || service apache2 start
 #
-## Allow write access to /var/www/html
-#sudo chmod 777 /var/www/html
+## Check if apache2 is running
+#if service apache2 status | grep -q "active (running)"; then
+#  echo "apache2 is running"
+#  else
+#    echo "apache2 failed to start"
+#      exit 1
+#      fi
 #
-## Ensure 'Hello Holberton' is returned
-#echo "Hello Holberton" | sudo tee /var/www/html/index.html
+#      # Create an index.html page with "Hello Holberton"
+#      echo "Hello Holberton" | sudo tee /var/www/html/index.html > /dev/null
 #
+#      # Restart Apache to apply changes
+#      service apache2 restart
